import argparse
import glob
import json


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('config', type=str)
    parser.add_argument('--log-dir', type=str, default='logs/')
    parser.add_argument('--plot-dir', type=str, default='plots/')
    return parser.parse_args()


def merge_log_files(files):
    """
    Merge Unity log files into one file.
    :param files: log files generated by Unity
    :return: merged log file
    """
    merged_data = []

    for file in files:
        with open(file, 'r') as f:
            data = json.load(f)
            for item in data["configurations"]:
                merged_data.append({
                    "screenshotID": item["screenshotID"],
                    "classOfObject": item["classOfObject"]
                })

    return merged_data


def find_label_by_identifier(identifier):
    """
    Find label by identifier.
    :param identifier: the object identifier.
    :return: label
    """
    with open('../objaverse/parsed_lvis_annotations.json') as f:
        annotations = json.load(f)

    label = annotations[identifier]
    return label