model:
  model_folders:
    - combined_f_combined
    - combined_r_combined
    - combined_fx_combined
  model_name: resnet18

data:
  root: ../data/
  backgrounds:
    - meadow
    - forest
    - desert
    - industrial
  views:
    - f
    - r
    - fx
  resolution: f