data:
  eval:
    num_classes: 32
    view:
      - f
      - r
      - er
      - fx
      - cr
    background:
      - meadow
      - forest
      - desert
      - industrial
    res: f

model:
  to_eval:
    backbone: resnet18
    view:
#      - f
#      - r
      - er
#      - fx
    res: combined
    background:
      - combined
    max_epoch: 30