data:
  eval:
    num_classes: 32
    view:
      - f
      - r
      - fx
      - er
      - cr
    suffix:

model:
  backbone: resnet18
  to_eval:
    view:
#      - f
#      - r
      - er
#      - fx
    res: combined
    background:
      - combined
    max_epoch: 30