data:
  root: ../data/robustness/ood_fx

distortion_types:
  - gaussian_noise
  - shot_noise
  - impulse_noise
  - speckle_noise
  - gaussian_blur
  - glass_blur
  - defocus_blur
  - motion_blur
  - zoom_blur
  - fog
  - frost
  - snow
  - spatter
  - contrast
  - brightness
  - saturate
  - jpeg_compression
  - pixelate
  - elastic_transform