log:
  log_folders:
    - grey_f_f
    - grey_r_f
#    - meadow_f_f
#    - meadow_r_f
    - forest_f_f
    - forest_r_f
#    - desert_f_f
#    - desert_r_f
#    - industrial_f_f
#    - industrial_r_f
  cue_conflict: cue_conflict_meadow_f_f

model:
  model_name: resnet18

plot:
  acc_min: 0
  acc_max: 1
