data:
  root: ../data/cue_conflict_meadow_f_f

model:
  model_folders:
    - mixed_f_f_25
    - mixed_f_f_50
    - mixed_f_f_90
    - mixed_r_f_10
    - mixed_r_f_25
    - mixed_r_f_50
    - mixed_r_f_90
  model_name: resnet18
