log:
  view:
    - f
    - r
    - fx
  res:
    - f
  biased_ratios:
    - 0.1
    - 0.25
    - 0.3
    - 0.5
    - 0.7
    - 0.9

model:
  model_name: resnet18

plot:
  acc_max: 100
  acc_min: 0
  loss_max: 5
  loss_min: 0
