log:
  view:
    - f
    - r
    - er
    - fx
  test_view:
    - cr
  background:
    - combined
  res: combined

model:
  model_name: resnet18
  max_epoch: 30

plot:
  loss_min: 0
  loss_max: 7.05
  acc_min: 0
  acc_max: 105
  loss_change_min: -1
  loss_change_max: 5
  acc_change_min: -80
  acc_change_max: 5
  palette:
    f : "#FF1F5B"
    r: "#00CD6C"
    er: "#AF58BA"
    fx: "#009ADE"
  view:
    - "Full view"
    - "Restricted view"
    - "Extra R. view"
    - "Fixed view"



