log:
  view:
    - f
    - r
    - fx
  res:
    - combined
  background:
#    - meadow
#    - forest
#    - industrial
#    - desert
    - combined

model:
  model_name: resnet18

plot:
  loss_min: 0
  loss_max: 5
  acc_min: 0
  acc_max: 100


