log:
  view:
    - f
    - r
    - er
    - fx
  background:
    - combined
  res: combined
  eval:
    view:
      - test_f
      - test_r
      - test_er
      - test_fx
    ood_view:
      - cr
    type:
      - border_cam
      - border_cam_cue_conflict_shape
      - border_cam_cue_conflict_texture
      - grand_cam_distorted

plot:
  palette:
    f : "#FF1F5B"
    r: "#00CD6C"
    er: "#AF58BA"
    fx: "#009ADE"
  view:
    - "Full view"
    - "Restricted view"
    - "Extra R. view"
    - "Fixed view"
  cam_types:
    - ic
    - bc
    - ec