log:
  view:
    - fx
    - er
    - r
    - f
  background:
    - combined
  res: combined
  eval:
    view:
      - f
      - r
      - er
      - fx
      - cr
    ood_view:
      - cr
    suffix:

model:
  model_name: resnet18
  max_epoch: 30

plot:
  loss_min: 0
  loss_max: 5.05
  acc_min: 0
  acc_max: 105
  loss_change_min: -1
  loss_change_max: 5
  acc_change_min: -80
  acc_change_max: 5
  decision_proportion_min: 0
  decision_proportion_max: 0.26
  shape_bias_min: 0
  shape_bias_max: 0.26
  palette:
    fx: "#009ADE"
    er: "#AF58BA"
    r: "#00CD6C"
    f : "#FF1F5B"
  palette_shape_bias:
    shape_and_texture_proportion: "#A0B1BA"
    shape_proportion: "#FFC61E"
    texture_proportion: "#F28522"
    shape_bias: "#AF58BA"
  view:
    - "Fixed view"
    - "Extra restricted view"
    - "Restricted view"
    - "Full view"
  shape_bias_metric:
    - "Shape and Texture Decision Ratio"
    - "Shape Decision Ratio"
    - "Texture Decision Ratio"
    - "Shape Bias"
  distortion_types:
    - gaussian_noise
    - shot_noise
    - impulse_noise
    - speckle_noise
    - gaussian_blur
    - glass_blur
    - defocus_blur
    - motion_blur
    - zoom_blur
    - fog
    - frost
    - snow
    - spatter
    - contrast
    - brightness
    - saturate
    - jpeg_compression
    - pixelate
    - elastic_transform
  max_severity: 5