log:
  log_folders:
    - mixed_f_f_0.1
    - mixed_f_f_0.25
    - mixed_f_f_0.3
    - mixed_f_f_0.5
    - mixed_f_f_0.7
    - mixed_f_f_0.9
#    - combined_f_combined
#    - combined_r_combined
#    - combined_fx_combined
#    - meadow_f_f
#    - forest_f_f
#    - industrial_f_f
#    - desert_f_f
#    - meadow_r_f
#    - forest_r_f
#    - industrial_r_f
#    - desert_r_f
#    - meadow_fx_f
#    - forest_fx_f
#    - industrial_fx_f
#    - desert_fx_f
  cue_conflict: cue_conflict_mixed

model:
  model_name: resnet18

plot:
  prefix: mixed_f
  acc_min: 0
  acc_max: 1
