data:
  background:
    - ood_meadow
    - ood_forest
    - ood_desert
    - ood_industrial
  view:
#   - f
#    - r
    - fx
  res:
    - f

sample:
  sample_num: 5
  output: robustness/ood_fx/content