data:
  test:
    batch_size: 32
    num_classes: 32
    view:
      - cr
    no_split:
      - cr
      - cr_no_obj
    res:
      - f
    background:
      - meadow
      - forest
      - desert
      - industrial

model:
  backbone: resnet18
  pretrained: false
  instance: 1
  to_test:
    view:
      - f
      - r
      - er
      - fx
    res:
      - combined
    background:
      - combined
    max_epoch: 30

